### ISSUE TITLE
Suggestion: On `/add` display current time according to account preferences

### ISSUE THREAD

**Issue by chiroptical** [NorfairKing/tickler#6]
On `/add` it would be helpful to display the current time according to your account preferences. This brings up another question:

- Should I be able to schedule something in the past?
    - If it just automatically fires the trigger than it is equivalent to `intray add ...` so I guess that is fine?

(I plan to try implementing this feature)

**Comment by NorfairKing** [comment]
@chiroptical 

The timezone is only applicable for the time you schedule something for. The time that something is being scheduled is stored in UTC, not localtime.
Could you elaborate on why you want to see the current time?

Yes you are able to schedule things in the past, it will just be triggered immediately.

**Comment by chiroptical** [comment]
The first test I did was to schedule something for an hour from now. As an example, it is currently 5 pm and I want to schedule something at 6 pm. In the web API on tickler.cs-syd.eu, because the default is UTC, 6 pm is actually 2 pm (I am in UTC-4) and therefore I scheduled in the past. If you added something like,

> The current time is {time} and you can change your time zone at /account

It would help clarify that,
- The server is in UTC time by default
- You can change the time zone in your account settings

**Comment by NorfairKing** [comment]
Aha, I get it!

It would be nice if the server could somehow figure out your timezone, but I have no idea how that would work. Google calendar seems to do it fine.

I'm curious about your workflow. Why would you want to have something tickled an hour from now? That's a use-case I'm not familiar with. Usually I use tickler using a day as the minimal granularity.

**Comment by chiroptical** [comment]
> It would be nice if the server could somehow figure out your timezone, but I have no idea how that would work

Same. I guess you just ask them? Just allow a user to set it directly from `/add`

> I'm curious about your workflow.

I don't have a workflow that needs this. I was just testing the website out and got confused by time zones.
